apiVersion: apps/v1
kind: StatefulSet                 # Type of Kubernetes resource
metadata:
  name: asterisk           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  serviceName: "astcluster"
  selector:
    matchLabels:
      app: asterisk        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: asterisk
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-voice/openline-asterisk-server:latest
          name: asterisk
          imagePullPolicy: Never
          env:
            - name: LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PUBLIC_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: CHANNELS_API_KEY
              value: 92c04073-17c3-4e91-8326-516bbd0750a4
            - name: CHANNELS_API_SERVICE
              value: http://channels-api-service.openline.svc.cluster.local:8013
            - name: GLADIA_API_KEY
              value: set_me
