apiVersion: apps/v1
kind: Deployment                 # Type of Kubernetes resource
metadata:
  name: kamailio           # Name of the Kubernetes resource
spec:
  replicas: 1                    # Number of pods to run at any given time
  selector:
    matchLabels:
      app: kamailio        # This deployment applies to any Pods matching the specified label
  template:                      # This deployment will create a set of pods using the configurations in this template
    metadata:
      labels:                    # The labels that will be applied to all of the pods in this deployment
        app: kamailio
    spec:                        # Spec for the container which will run in the Pod
      containers:
        - image: ghcr.io/openline-ai/openline-voice/openline-kamailio-server:latest
          name: kamailio
          imagePullPolicy: Never
          env:
            - name: LOCAL_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: PUBLIC_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: AUTH_SECRET
              value: 2c42a1b6-d776-4083-b0b6-44fecea2d022
            - name: SQL_USER
              value: openline
            - name: SQL_PASSWORD
              value: password
            - name: SQL_DATABASE
              value: openline
            - name: SQL_HOST
              value: customer-db-postgresql.openline.svc.cluster.local
            - name: ASTERISK_HOST
              value: asterisk.openline.svc.cluster.local
            - name: HOMER_IP
              value: 127.0.0.2
            - name: APIBAN_KEY
              value: invalid
            - name: DMQ_DOMAIN
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
