apiVersion: v1
kind: Service                    
metadata:
  name: kamailio-loadbalancer-service   
spec:
  type: LoadBalancer
  ports:
    - name: ws                    
      port: 8080
      targetPort: 8080
    - name: sip
      port: 5060
      targetPort: 5060
      protocol: UDP
    - name: sip-tcp
      protocol: TCP
      port: 5060
      targetPort: 5060
  selector:
    app: kamailio         
