apiVersion: v1
kind: Service                    
metadata:
  name: voice-plugin-service   
spec:
  type: NodePort                 
  ports:
    - name: http                    
      port: 11010
      targetPort: 11010
  selector:
    app: voice-plugin
