apiVersion: v1
kind: Service                    
metadata:
  name: kamailio-service   
spec:
  type: NodePort                 
  ports:
    - name: ws                    
      port: 8080
      targetPort: 8080
    - name: sip
      protocol: UDP
      port: 5060
      targetPort: 5060
  selector:
    app: kamailio         