# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Asterisk Toolchain

on:
  push:
    branches: [ "otter"]
    paths:
      - 'packages/server/asterisk/**'
      - '.github/workflows/asterisk.yml'
  pull_request:
  release:
    types: [created, edited]

permissions:
  contents: read

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/openline-asterisk-server


jobs:
    publish:
      name: "Push Asterisk Docker Image"
      if: github.ref_name == 'otter' || github.event_name == 'release'
      runs-on: ubuntu-latest

      steps:
        - name: Checkout
          uses: actions/checkout@v3

        - name: Log in to the Container registry
          uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
          with:
            registry: ${{ env.REGISTRY }}
            username: ${{ secrets.REPOSITORY_READ_WRITE_USERNAME }}
            password: ${{ secrets.REPOSITORY_READ_WRITE_TOKEN }}

        - name: Extract metadata (tags, labels) for Docker
          id: meta
          uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
          with:
            images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

        - name: Push Docker image
          uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
          with:
            context: packages/server/asterisk
            file: packages/server/asterisk/Dockerfile
            push: true
            tags: ${{ steps.meta.outputs.tags }}
            labels: ${{ steps.meta.outputs.labels }}
